name: Django workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r requirements.txt

      - name: run pep8 tests
        run: python -m flake8

      - name: run app tests
        run: python infra_project/manage.py test

  build_push_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: kv1o/practicum-django:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_docker_hub
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRACTICUM_HOST }}
          username: ${{ secrets.PRACTICUM_USER }}
          key: ${{ secrets.PRACTICUM_SSH_KEY }}
          scripts: |
            sudo docker pull kv1o/practicum-django
            sudo docker stop ${docker ps -aq}
            sudo docker run -- rm -d -p 5000:5000 kv1o/practicum-django